### ISSUE TITLE
[FormBuilderDateTimePicker] with samsung keyboard number display only

### ISSUE THREAD

**Issue by ducdac** [flutter-form-builder-ecosystem/flutter_form_builder#1025]
![image](https://user-images.githubusercontent.com/49010784/169210872-38195dc2-20f7-4241-89cf-1dd8eb5a63f4.png)

**Comment by danvick** [comment]
To change the input mode for your FormBuilderDateTimePicker, use the `initialEntryMode` attribute, like so: 

```Dart
FormBuilderDateTimePicker(
    name: 'date',
    initialEntryMode: DatePickerEntryMode.calendar,
    initialValue: DateTime.now(),
}
```

Note: The calendar icon on the top right allows you to switch between the different input modes.

**Comment by danvick** [comment]
Kindly let us know if this solves your problem

**Comment by ducdac** [comment]
@danvick my code:
`FormBuilderDateTimePicker(
    name: 'date',
    inputType: InputType.date,
    keyboardType: TextInputType.datetime,
    initialValue: control.phieumuahang.ngayPhieu,
    format: f.getDateFormat(),
    locale: const Locale('de', 'DE'),
  ),`
initialEntryMode default is  DatePickerEntryMode.calendar, when i click on the top right icon only the numeric keypad shows.
it only works on samsung devices, but on other devices, it shows the correct datetime keyboard

**Comment by deandreamatias** [comment]
Hi @ducdac 
This package use the default inputs from material to build the form inputs.
I found some issues related in flutter repository:

- https://github.com/flutter/flutter/issues/71670
- https://github.com/flutter/flutter/issues/62401
- https://github.com/flutter/flutter/issues/59685

I think that this problem is originated by flutter dependency
