### ISSUE TITLE
Is it possible to apply valueTransformer before validation?

### ISSUE THREAD

**Issue by getpoucher** [flutter-form-builder-ecosystem/flutter_form_builder#1071]
Hello,

I have a `FormBuilderTextField` of type email that I would like to have its value trimmed with `valueTransformer` before calling `_formKey.currentState!.validate`. I thought that when calling `_formKey.currentState!.save()` the transformations were applied.

Is it possible to do it?

Thanks in advance

**Comment by deandreamatias** [comment]
Hi!
When you call validate(), the Vale isn't transformed?

**Comment by CaLouro** [comment]
This might be a limitation between the interaction of the package code and Flutter code. `validate` is a function of the Flutter `Form` and `FormField`s, where the transformers are a thing from the package. FlutterFormBuilder does not actually call the transformers on a field's value until you call the getters `value` and `instantValue`. 

Saving a transformed value inside the field's value attribute to be validated could lead to type errors because `FormFieldState<T>` is typed beforehand. In your use case, just trimming should not change the type but the transformers were made to... well... transform the value and type of the input.

Changing the transformer to support that use case is an interesting idea that I too have come across in the past but at this point it would require a significant code re-write and decoupling from the Flutter `Form` API, as far as I can understand.

As a suggestion, could `inputFormatters` work? I have never use them for trimming a field but it could be worth looking into it.

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the question still exists, feel free to reopen or open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
