### ISSUE TITLE
License change to GPLv3?

### ISSUE THREAD

**Issue by flutterfromscratch** [flutter-form-builder-ecosystem/flutter_form_builder#1091]
First seen in this commit: https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/commit/d3fe0c5db00c52713605d1b68e52855833b46c9b#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7

The license of flutter_form_builder has changed from BSD 2-Clause to GPL v3. To my understanding, this means that if I use flutter_form_builder in any application, I must release the source code to that application (I'm not a lawyer).

So, I guess some questions arise from this:
1. Was this license change intentional? It seemed to occur when a lot of files were moved
2. Can people "purchase" a version of flutter_form_builder that is not under GPLv3?
3. Can I safely use older versions of flutter_form_builder that are not under GPLv3?

Thanks for all your hard work on flutter_form_builder

**Comment by flutterfromscratch** [comment]
I can see that @deandreamatias changed the license to GPLv3 in related packages (in this commit https://github.com/flutter-form-builder-ecosystem/form_builder_file_picker/commit/7aa31c7702f5ff6a787489af4a8601f8e16f5651).

**Comment by deandreamatias** [comment]
Hi @flutterfromscratch!
Thanks for your question.

I try to explain all about license.
Context: My idea with this new license was improve the open source package to free source package.

Questions: 
1. Yes
2. A modified version of flutter_form_builder, no.
3. Yes

Revert changes: To avoid problems of compatibility, I back to BSD license. Now I add a [BSD-3-clause](https://opensource.org/licenses/BSD-3-Clause) license, but is only the new version of BSD-2. I updated a year and copyright holder too.

Conclusion: Because this package is used to commercial softwares without GPLv3 license, from what I've read, can't be posible add this package if this softwares can't has the same license that this package.

Thanks a lot for your important quesiton
