### ISSUE TITLE
FormBuilderCupertinoDateTimePicker() not defined

### ISSUE THREAD

**Issue by carlleeswanson** [flutter-form-builder-ecosystem/flutter_form_builder#1098]
The Change log for v7.3.0 indicates:
- Added new attribute timePickerTheme to FormBuilderCupertinoDateTimePicker

However, FormBuilderCupertinoDateTimePicker does not appear to be part of the current version (v7.5.0). Was it removed? Was it never included (in which case, why does the Change log refer to it)? This is very confusing to me.

Or is there something "special" that I need to include/import/do to use the Cupertino picker? There are no examples for it currently, and it is not listed in the "supported" fields. The Android picker is not suitable to use on an iOS device.

**Comment by deandreamatias** [comment]
Hi @carlleeswanson !
About widget:
- This widget that you need, can found in package [form_builder_extra_fields](https://github.com/flutter-form-builder-ecosystem/form_builder_extra_fields/blob/main/lib/src/fields/form_builder_cupertino_date_time_picker.dart).
- This widget is there because need an external dependency ([flutter_datetime_picker_bdaya](https://pub.dev/packages/flutter_datetime_picker_bdaya)). I don't know why was decided add this external dependency.

About changelog: 
- I start a short time ago [a discussion](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/discussions/1038) to improve support for this ecosystem packages. The wrong changelog is one of the things I want to avoid. I don't know why it is like that, but apparently it doesn't represent well the changes that have been made.

Thanks for your question and I am available if you need anything else

**Comment by carlleeswanson** [comment]
@deandreamatias  Thank you for clarifying!
