### ISSUE TITLE
The method 'FormBuilderDateTimePicker' isn't defined for the type  ''

### ISSUE THREAD

**Issue by hpwahyao** [flutter-form-builder-ecosystem/flutter_form_builder#1219]
Hi I tried to follow the sample code. but Flutter complains the error as 'The method 'FormBuilderDateTimePicker' isn't defined for the type XXX'. 

Looks like the way to use form builder date time picker is not correct. Any suggestion pls? 

<img width="1007" alt="Screenshot 2023-04-16 at 4 32 57 PM" src="https://user-images.githubusercontent.com/13344443/232286824-60f79b23-fd4e-42c3-be60-14e23516634a.png">

**Comment by deandreamatias** [comment]
Please add all info required by bug template to can try solve this issue. Template:

## Environment

**Package version:**

<details>
  <summary>Flutter doctor</summary>


```
```

</details>

<details>
  <summary>Code sample</summary>



```dart
```

</details>

## Description

**Expected behavior:**

**Current behavior:**

## Steps to reproduce

1. This
2. Than that
3. Then

## Images   

## Stacktrace/Logcat
