### ISSUE TITLE
[Feature Request] File Picker FormField

### ISSUE THREAD

**Issue by sumitbhanushali** [flutter-form-builder-ecosystem/flutter_form_builder#284]
Hi @danvick, it was great to see image picker included with your package, one of my app I am building requires file picker too, would it be possible to add it also?

I found this package stable and useful https://github.com/miguelpruivo/flutter_file_picker

**Comment by danvick** [comment]
Hi @sumitbhanushali,
Thanks for your contribution.

We, however, have a FilePickerFormField I had initially thought it wise to have it as a [separate package](https://pub.dev/packages/form_builder_file_picker) in a [separate repository](https://github.com/danvick/form_builder_file_picker) but my opinion has since changed and I'll be having it as part of the main repo in the next major version.

As at this moment, all you have to do is to [install the package](https://pub.dev/packages/form_builder_file_picker#-installing-tab-) and use it within FormBuilder in your project.

**Comment by danvick** [comment]
Hi @sumitbhanushali,
I've noticed that you reopened this issue. Kindly note that ImagePicker field was added to the package through a PR.

Is there a problem with the widget?

**Comment by sumitbhanushali** [comment]
> Hi @sumitbhanushali,
> Thanks for your contribution.
> 
> We, however, have a FilePickerFormField I had initially thought it wise to have it as a [separate package](https://pub.dev/packages/form_builder_file_picker) in a [separate repository](https://github.com/danvick/form_builder_file_picker) but my opinion has since changed and we'll be having it as part of the main repo in the next major version.
> 
> As at this moment, all you have to do is to [install the package](https://pub.dev/packages/form_builder_file_picker#-installing-tab-) and use it within FormBuilder in your project.

I had closed this issue by mistake then reopened it because filepicker is still not in this repo

**Comment by deandreamatias** [comment]
This package is created is separate repository in this organization
