### ISSUE TITLE
Various feedback

### ISSUE THREAD

**Issue by gilthonweapps** [flutter-form-builder-ecosystem/flutter_form_builder#335]
Hi,

First, thanks for that great plugin! It is very good and helps me a lot in my app.

I have several feedbacks/questions concerning the plugin:
- How can we have a translated list of countries for country picker? Obviously, not all apps are in English.
- I need to tap twice on the phone picker to have the focus and if the field is empty, the flag will only appear after the second tap.
- It would be nice to be able to start typing +XXX and have the country automatically selected based on the prefix. The field should also use a mask to format the number, e.g. +1 (123) 555-1234. If you use libphonenumber, you should be able to do all that.
- When using FormBuilderRadioGroup, it is not possible to use FormBuilderFieldOption with value and child as only the value is displayed, not the child.
- When the form is in readonly, it should be nice to hide all the clear buttons (e.g. date picker) and dropdown V icons.

Regards :)

**Comment by danvick** [comment]
Hi @gilthonweapps,
I'm glad you're finding this package useful and thanks for your contribution through your feedback.

First of all, I'd like to let you know that this package makes use of other packages some of which may come with some issues of their own. Your suggestions 1, 4, and 5 fall into such. 
We've had to raised issues or submit PRs to these repos just to solve such kinds of issues and other times maintain our own copy of such widgets so that we could make changes fast - which is quite inefficient.

As for issues 2 and 3 we'll consider having these improvements done - especially 2 which seems to be a bug of some kind.

Lastly, as a suggestion for the future kindly open different issues separately so that their progress could be tracked easily.

**Comment by ghprod** [comment]
Just came here because the same issue with `FormBuilderRadioGroup` is not able to set label and value independently. After digging the source code, confirmed, the issue is within another package.

Especially this line

https://github.com/TercyoStorck/group_radio_button/blob/master/lib/src/radio_group.dart#L43

**Comment by danvick** [comment]
I'm thinking, for this specific issue, we may be forced to make a copy of the widget and customize it to our satisfaction.

**Comment by NengSyle007** [comment]
Hi,

First, thanks for that great plugin! Yes, I want to this plugin have input mask for FormTextField and hope see it on next version.

**Comment by deandreamatias** [comment]
Hi @gilthonweapps!
Do you can review if still needed this suggestions?
If yes, please open separated issues for each of ones.
Thanks

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new separated issues](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
