### ISSUE TITLE
FormBuilderTypeAhead<T> relies on T's toString method for initialValue

### ISSUE THREAD

**Issue by dmoeyers** [flutter-form-builder-ecosystem/flutter_form_builder#624]
Hello,

I noticed that when you are using custom type T, its toString method is used to convert T to a String for the initialValue.

```
@override
  void initState() {
    super.initState();
    _typeAheadController = widget.controller ??
        TextEditingController(text: widget.initialValue?.toString());
    _typeAheadController.addListener(_handleControllerChanged);
  }
```

Wouldn't it be more logical to use selectionToTextTransformer here as well ?

Kind regards

**Comment by awhitford** [comment]
This inconsistency is really related to https://github.com/AbdulRahmanAlHamali/flutter_typeahead/issues/209.  There is really an API deficiency with the underlying `flutter_typeahead` package because there needs to be well-defined two-way translation.

Sorry, but this hasn't been addressed yet.  In the meantime, this is best used for String values.

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/danvick/flutter_form_builder/issues/new/choose)
