### ISSUE TITLE
support desktop and web app

### ISSUE THREAD

**Issue by YouSour** [flutter-form-builder-ecosystem/flutter_form_builder#667]
hi , do you have a plan to make this package support desktop and web app ?

**Comment by danvick** [comment]
Hi @YouSour,
In the latest versions of the package, we've [separated out mobile-dependent packages into their own packages](https://github.com/danvick/flutter_form_builder#additional-input-fields) so that the package core can support any platform.

**Comment by YouSour** [comment]
@danvick ok , i will check it. thank you so much for info , keep it up , good job  👍

**Comment by awhitford** [comment]
Please note that #600 is likely a showstopper because desktop support is in the **dev** channel, and FFB only compiles presently with the **stable** channel.

You can help us by voting for https://github.com/Realank/flutter_datetime_picker/issues/206 and https://github.com/Realank/flutter_datetime_picker/issues/197.  We need to get that author's attention to resolve critical issues from the dependent project.

**Comment by deandreamatias** [comment]
Related with #350

**Comment by deandreamatias** [comment]
The package [flutter_form_builder](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder) is compatible with web. 
Have a desktop support too, but hasn't examples to this. Will be track this in #350

Now we need supported [other packages of ecosystem](https://pub.dev/publishers/flutterformbuilderecosystem.com/packages), but this issue need to be created is each other repositories
