### ISSUE TITLE
FormBuilderDropdown assert error with initialValue 

### ISSUE THREAD

**Issue by KanybekMomukeyev** [flutter-form-builder-ecosystem/flutter_form_builder#687]
Hi, thanks for sharing source codes!
But FormBuilderDropdown has a serious issue, every time when i am trying to update UI with new items, i have a following issue:

```
assert(items == null || items.isEmpty || value == null ||
              items.where((DropdownMenuItem<T> item) {
                return item.value == value;
              }).length == 1,
                "There should be exactly one item with [DropdownButton]'s value: "
                '$value. \n'
                'Either zero or 2 or more [DropdownMenuItem]s were detected '
                'with the same value',
              ),
```

I have allready removed FormBuilderDropdown, and directly used with same source code DropdownButton,
everything is worked like a charm, no problem. By me the problem of FormBuilderDropdown is "initialValue"
the "initialValue" may be not updating, i will try to detail research this issue, but issue is exsists 100%.

**Comment by andrewzakhartchouk** [comment]
Can you share your code of the `FormBuilderDropdown` that is causing the problem?

**Comment by Chappie74** [comment]
This seems to be occurring when the inital value of the dropdown is an empty string, well for me at least. 
![image](https://user-images.githubusercontent.com/21108487/105508066-4f4f8180-5ca2-11eb-8170-2c51d02efdd2.png)

There are times when my initial value will be empty, because i am using the same form to add/edit. I would expect that if its an empty string it would show the default  label text, but it throws the error instead.
![image](https://user-images.githubusercontent.com/21108487/105508232-8756c480-5ca2-11eb-9c6c-f1d50e7c4bd2.png)

**Comment by andrewzakhartchouk** [comment]
If you declare _initialValue_, then you can't leave it blank. 
An easy fix is using a ternary operator `?` to make sure _initialValue_ always has a value. This includes an empty/null value.

eg:
`initialValue: data != null ? data : null`

In the case of a FormBuilderDropdown, returning a `null` value works.
Something like a FormBuilderFilterChip however requires a list `[]`.

**Comment by derolf** [comment]
Empty string might be a valid drop down value, so empty and null must be treated differently

**Comment by YouSour** [comment]
anyone can solve this problem ?

**Comment by mdeandrea-mrmilu** [comment]
This issue is resolved?
If not, please update generic title to specific

**Comment by deandreamatias** [comment]
This issue still happens in version 7.3.1

**Comment by tonypottera24** [comment]
I'm facing the same problem.
I think the core reason is the `FormBuilderDropdown.initialValue` tried to insert a `DropdownMenuItem` into the `FormBuilderDropdown.items` list.

**Comment by tonypottera24** [comment]
Same issue even if the text is not null.

**Comment by Chappie74** [comment]
I've since opted out of using this. Found a much better and cleaner solution.  Those familiar with react may feel right at home. 

https://pub.dev/packages/reactive_forms

**Comment by tonypottera24** [comment]
I just resolved my issue.
Assume we use `int` as the value of `DropdownMenuItem`
i.e.
```
items = [
DropdownMenuItem<int>(
      value: 100,
      child: Text('Apple'),
),
DropdownMenuItem<int>(
      value: 200,
      child: Text('Orange'),
)
]
```
The value of `FormBuilderDropdown.initialValue`  must also be an `int` (100 or 200).

**Comment by KanybekMomukeyev** [comment]
@Chappie74 why i should use ReactiveForm, what addition required feature it gives me?
I use Native from builder, and everything seems to be ok. Just for interesting.

**Comment by Chappie74** [comment]
@KanybekMomukeyev I can't remember why I switched since it was a year or so ago. But I'm sure it was due to having troubles with this package. 
You can use whatever works for you. 
You can also take a read at the docs for reactive forms, maybe you'll find something you'd like.

**Comment by PongsiriTK** [comment]
This issue still happen when I use state management to update item list. DropDownMenuItem still remember the previous values and throw an error 

There should be exactly one item with [DropdownButton]'s value: 3.
Either zero or 2 or more [DropdownMenuItem]s were detected with the same value

**Comment by deandreamatias** [comment]
If someone can share some minimal example code and steps to reproduce the issue, I really will appreciate

**Comment by WasimMemon** [comment]
> If someone can share some minimal example code and steps to reproduce the issue, I really will appreciate

This issue still happens.  (flutter_form_builder: ^7.7.0)
I have created gist from my code - https://gist.github.com/WasimMemon/3fa67ad821db2be90582bea3521c8afe
Please check and let us know solution for it.

**Comment by delhiguy100** [comment]
I had the same problem. Turns out the problem was in my code - it is working perfectly now. The mistake I did was to give same name to two fields in the same form. The error went away after making the names unique.

If there are others still facing this issue, please verify you haven't made the same mistake - hope it helps.

**Comment by miguelflores1993** [comment]
same problem.....

**Comment by jastranlove2020** [comment]
After 02 years, this bug is still open. Change the list of items to new one, and change initial value raising this bug obviously.

**Comment by deandreamatias** [comment]
After a 2 years, no one can help to debug this.
This is a open source code, everyone can contribute to solve this problem. Please, feel free to do it

**Comment by jastranlove2020** [comment]
Test case for this error:
1> First FormBuilderDropdown is for country list loaded from FutureProvider
2> Second FormBuilderDropdown is for City, depend on the first FormBuilderDropdown, when the first one changes, then second FormBuilderDropdown will be also changed, the Second one is also loaded from FutureProvider.

On the first scenario, the screen is loaded with both FormBuilderDropdown (having name country) with initial value is USA and another FormBuilderDropdown (having name City) with initial value California.

On the second scenario, change the Country value to France, and the City will be refreshed the list with rebuilding the widget with inital value empty, then error will be raised by Dropdown button assert.  


I do temporary fix by control the name dynamic, so that FormBuilderDropdown will be rebuilt with unique name, then i will get the latest unique name.

Hope this will help someone  with the useful package.

Brian N, senior engineer.

<img width="249" alt="image" src="https://user-images.githubusercontent.com/76111758/236627344-f8de34d0-15c2-4342-a473-9a9c91be95f9.png">

**Comment by deandreamatias** [comment]
Solved :)
Was so simple, but I really needed try a lot of things to debug and solve the problem

**Comment by deandreamatias** [comment]
Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)

**Comment by jastranlove2020** [comment]
> Can test this on [pre-release 9.0.0-dev.1](https://pub.dev/packages/flutter_form_builder/versions/9.0.0-dev.1)

Tested with this version, it is fine without the bug. You can release it for production use. Thank you so much.

**Comment by deandreamatias** [comment]
Thanks you @jastranlove2020 for help to debug this
I will release in a two weeks I guess, because has a breaking changes that need validate
