### ISSUE TITLE
dynamically add/remove widget with form_builder fields

### ISSUE THREAD

**Issue by tas-unn** [flutter-form-builder-ecosystem/flutter_form_builder#920]
How to add and remove widgets dynamically on a form? with unique names and correct deletion.
I do not normally delete elements. In addition, after deleting, you need to double-click on the plus to add the item.

i tried 
1) in _PersonalState i create list widget
static List<Widget> ws=List.empty(growable: true);
int _numparents=0;

2) i create class

class Parents extends StatefulWidget {
  const Parents({Key? key,required int this.id}) : super(key: key);
  final int id;

  @override
  _ParentsState createState() => _ParentsState();
}

class _ParentsState extends State<Parents> {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        ElevatedButton(onPressed: () { int _i=0;
        for (var element in _PersonalState.ps) {
        {
          if (element.id==widget.id) { _PersonalState.ps.removeAt(_i); break;}
          _i++;
        }; },
        child:Text("-")),
        FormBuilderTextField(
           initialValue: widget.id.toString(),
          
          name: 'whopass'+widget.id.toString(),
         
        ),
      ],
    );
  }
}
3) and in buildwidget i create adding button

ElevatedButton(onPressed: () {setState(() {
          _numparents++;
          _ParentsWidgets.add(Parents(id:_numparents));}
        });},child:Text("+"))

**Comment by WilliamCunhaCardoso** [comment]
`registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?

**Comment by globalwebforce** [comment]
> `registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?

Author like you should be banned on Flutter, your answer is always the same on different questions, the worst thing is, it's non-sense, not useful and not testable, I hope this will be your last package.

**Comment by phantomate** [comment]
> `registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?

Hi, could you please provide a small example on how to use registerField? I have no idea which FormBuilderFieldState I have to provide to registerField nor how to get that State from the FormBuilderTextField Widget

**Comment by tas-unn** [comment]
Yes17:25, 10 июня 2022 г., Matias de Andrea ***@***.***>:
This still an issue?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by CaLouro** [comment]
I don't understand why is this still a problem. I've being using dynamic fields with version 7.2.1 and 7.3.1 and didn't have problems with adding and removing fields on state change. 

> with unique names and correct deletion

Especially if they will have different names, I can't see it being a big problem. @tas-unn could you please explain a little bit more what was going wrong with the way you were trying?

**Comment by deandreamatias** [comment]
@tas-unn please test the latest version of package and report if this issue still happend

@globalwebforce read our [Code of Conduct](https://github.com/flutter-form-builder-ecosystem/.github/blob/main/CODE_OF_CONDUCT.md). Your replay isn't accept in this organization because don't being respectful with one of our maintainers. If you continues, we will can restrict or ban access to this organization.

> > `registerField` and `removeInternalFieldValue` from `formKey` `currentState` does not satisfy your situation?
> 
> Author like you should be banned on Flutter, your answer is always the same on different questions, the worst thing is, it's non-sense, not useful and not testable, I hope this will be your last package.

**Comment by accsuresh** [comment]
Hello, 

I need inputs on my issue:

I have a FormBuilder with a Card one form builder dropdown. based on the selection I need to populate another card   containing couple of form builder dropdown fields, couple of form builder text fields.
The form will always have one card at-least and optionally additional cards can be added as required.
The first card contains an Add button to add subsequent cards.

I am using a list to maintain all added cards as well as all they global keys for dropdown controls within the card. 
I have the names for the first fixed card like item1_1, item2_1, item3_1 etc.
For all the added cards I am using the names like 
item1_(index+2),  item2_(index+2),  item3_(index+2),  etc

I am able to add items to the list and render them on screen with listview item builder, my issue is when removing a card between the first and last. Since I have the field names based on the index value It has become an issue when removing an item from the middle.
Any thoughts on how to fix this?
